### ISSUE TITLE
Add Maïté to the coordination team

### ISSUE THREAD

**Issue by archived-m** [HackYourFutureBelgium/website-old#11]

**Comment by Maycldts** [comment]
Change Coordindation Team to : '**Team**' with Dries, Manon and Julia as '**Co-Founde**r' and Maite as '**Coordinator**'.

**Comment by Maycldts** [comment]
Please find my contact details below:
LinkedIn: linkedin.com/in/mcluydts
Twitter: https://twitter.com/MaiteCluydts
Email: maite@hackyourfuture.be
