### ISSUE TITLE
Update Applications dates

### ISSUE THREAD

**Issue by Maycldts** [HackYourFutureBelgium/website-old#14]
Remove : 
Apply now for class #4, which starts on 17 March 2019.

Change by:
Apply now for class #5, which starts on 26 May 2019.

**Comment by archived-m** [comment]
Deployed in https://github.com/HackYourFutureBelgium/HackYourFutureBelgium.github.io/commit/9950405bf5f2047ae45e4cdb6584d6e02120d3f4
