### ISSUE TITLE
Button: APPLY NOW

### ISSUE THREAD

**Issue by Maycldts** [HackYourFutureBelgium/website-old#16]
**Can you please replace the link of the button by the following:** 

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSf5lqmVhTPQPbz-y4vr3_sVtfhPar4InYcgXQhVXRJmj3nQVw/viewform?embedded=true" width="640" height="764" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe> 

or 

https://docs.google.com/forms/d/e/1FAIpQLSf5lqmVhTPQPbz-y4vr3_sVtfhPar4InYcgXQhVXRJmj3nQVw/viewform?usp=sf_link

**Comment by archived-m** [comment]
@Maycldts Is this issue still relevant?
